#######
# Compiled from data/woutbelt/functions/blue_enter.mcscript
# to .//woutbelt/data/woutbelt/functions/blue_enter.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @s[y_rotation=-90..91] run playsound minecraft:block.end_portal_frame.fill master @s ~ ~ ~ 200 0
execute as @s[y_rotation=-90..91] run particle minecraft:end_rod ~ ~ ~ 0 1 0 .2 20
execute as @s[y_rotation=-90..91] run tp @s ~ ~ ~-47
execute as @s[y_rotation=-90..91] run particle minecraft:end_rod ~ ~ ~ 0 1 0 .2 20