#######
# Compiled from data/woutbelt/functions/enter.mcscript
# to .//woutbelt/data/woutbelt/functions/enter.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set @s woutbelt_timer 0
