#######
# Compiled from data/woutbelt/functions/plot_on.mcscript
# to .//woutbelt/data/woutbelt/functions/plot_on.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard objectives add woutbelt_timer dummy
bossbar add woutbelt:woutbelt_red {"text":"❋","font":"woutbelt:woutbelt","type":"text"}
bossbar add woutbelt:woutbelt_blue {"text":"✾","font":"woutbelt:woutbelt","type":"text"}
execute positioned ~ ~8 ~-23 run function woutbelt:portal_display
execute positioned ~ ~8 ~24 run function woutbelt:portal_display

return 1