#######
# Compiled from data/woutbelt/functions/portal_display.mcscript
# to .//woutbelt/data/woutbelt/functions/portal_display.mcfunction
#
# Generated by Minecraft Script for 1.16
######
summon minecraft:text_display ~ ~ ~ {brightness:{block:0,sky:15},text:'{"text":"❋","font":"woutbelt:default"}',Rotation:[180f,0f]}
summon minecraft:text_display ~ ~ ~ {brightness:{block:0,sky:15},text:'{"text":"❤","font":"woutbelt:default"}',Rotation:[0f,0f]}