#######
# Compiled from data/woutbelt/functions/portal_display.mcscript
# to .//woutbelt/data/woutbelt/functions/portal_display.mcfunction
#
# Generated by Minecraft Script for 1.16
######
summon minecraft:text_display ~ ~ ~ {brightness:{block:0,sky:15},text:'{"text":"❋","font":"woutbelt:default","type":"text"}',Rotation:[180.0f,0.0f]}
summon minecraft:text_display ~ ~ ~ {brightness:{block:0,sky:15},text:'{"text":"❤","font":"woutbelt:default","type":"text"}',Rotation:[0.0f,0.0f]}
return 1