#######
# Compiled from data/woutbelt/functions/tick_plot.mcscript
# to .//woutbelt/data/woutbelt/functions/tick_plot.mcfunction
#
# Generated by Minecraft Script for 1.16
######

execute as @a[tag=pr.target] at @s if score @s woutbelt_timer matches ..0 if block ~ ~-2 ~ minecraft:red_concrete run function woutbelt:red_enter
execute as @a[tag=pr.target] at @s if score @s woutbelt_timer matches ..0 if block ~ ~-2 ~ minecraft:light_blue_concrete run function woutbelt:blue_enter
execute as @a[tag=pr.target] at @s if score @s woutbelt_timer matches ..0 if block ~ ~-3 ~ minecraft:red_concrete run function woutbelt:red_enter
execute as @a[tag=pr.target] at @s if score @s woutbelt_timer matches ..0 if block ~ ~-3 ~ minecraft:light_blue_concrete run function woutbelt:blue_enter
execute as @a[tag=pr.target] at @s if score @s woutbelt_timer matches ..0 if block ~ ~-4 ~ minecraft:red_concrete run function woutbelt:red_enter
execute as @a[tag=pr.target] at @s if score @s woutbelt_timer matches ..0 if block ~ ~-4 ~ minecraft:light_blue_concrete run function woutbelt:blue_enter
execute as @a[tag=pr.target] at @s if score @s woutbelt_timer matches ..0 if block ~ ~-5 ~ minecraft:red_concrete run function woutbelt:red_enter
execute as @a[tag=pr.target] at @s if score @s woutbelt_timer matches ..0 if block ~ ~-5 ~ minecraft:light_blue_concrete run function woutbelt:blue_enter
execute as @a[tag=pr.target] at @s if score @s woutbelt_timer matches ..0 if block ~ ~-6 ~ minecraft:red_concrete run function woutbelt:red_enter
execute as @a[tag=pr.target] at @s if score @s woutbelt_timer matches ..0 if block ~ ~-6 ~ minecraft:light_blue_concrete run function woutbelt:blue_enter
execute as @a[tag=pr.target] at @s if score @s woutbelt_timer matches ..0 if block ~ ~-7 ~ minecraft:red_concrete run function woutbelt:red_enter
execute as @a[tag=pr.target] at @s if score @s woutbelt_timer matches ..0 if block ~ ~-7 ~ minecraft:light_blue_concrete run function woutbelt:blue_enter
execute as @a[tag=pr.target] at @s if block ~ ~9 ~ minecraft:lime_wool run tp @s ~ ~ ~24
execute positioned ~ ~5 ~-23 run particle minecraft:ash ~ ~ ~ 2 1 0 0 5
execute positioned ~ ~5 ~-23 as @a[distance=..12,tag=pr.target] run tag @s add woutbelt_blue
execute positioned ~ ~5 ~-23 as @a[distance=..12,tag=pr.target] run tag @s remove woutbelt_red
execute positioned ~ ~5 ~23 run particle minecraft:ash ~ ~ ~ 2 1 0 0 5
execute positioned ~ ~5 ~23 as @a[distance=..12,tag=pr.target] run tag @s add woutbelt_red
execute positioned ~ ~5 ~23 as @a[distance=..12,tag=pr.target] run tag @s remove woutbelt_blue
bossbar set woutbelt:woutbelt_blue players @a[tag=woutbelt_blue,tag=pr.target]
bossbar set woutbelt:woutbelt_red players @a[tag=woutbelt_red,tag=pr.target]

return 1